
---
- name: Install tomcat
  hosts: target_nodes
  gather_facts: no

  tasks:
    - name: Check if Java is already installed
      shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
      register: java_version

    - debug:
        msg: Installed Java version is {{java_version.stdout}}
      when: java_version is success

    - name: Copy tomcat
      copy:
        src: files/apache-tomcat-{{tomcat_version}}.tar.gz
        dest: /tmp/apache-tomcat-{{tomcat_version}}.tar.gz

    - name: Create group tomcat
      group:
        name: "{{tomcat_group}}"
        state: present
    - name: Create user tomcat
      user:
        name: "{{tomcat_user}}"
        state: present

    - name: Create directory "{{inst_root}}"/apache-tomcat-{{tomcat_version}}
      file:
        path: "{{inst_root}}/apache-tomcat-{{tomcat_version}}"
        state: directory
        owner: "{{tomcat_group}}"
        group: "{{tomcat_user}}"
        mode: "0755"

    - name: Install tomcat
      unarchive:
        src:  /tmp/apache-tomcat-{{tomcat_version}}.tar.gz
        dest: "{{inst_root}}/apache-tomcat-{{tomcat_version}}"
        remote_src: yes
        extra_opts: "--strip-components=1"
        owner: "{{tomcat_group}}"
        group: "{{tomcat_user}}"
        creates: "{{inst_root}}/apache-tomcat-{{tomcat_version}}/bin"
        mode: "0755"

    - name: Replace tomcat-users.xml file
      copy:
        src: files/tomcat-users.xml
        dest: "{{inst_root}}/apache-tomcat-{{tomcat_version}}/conf/tomcat-users.xml"
        owner: "{{tomcat_group}}"
        group: "{{tomcat_user}}"

    - name: Add startup script (systemd unit file)
      copy:
        src: files/tomcat.service
        dest: /etc/systemd/system/tomcat.service

    - name: Daemon reload
      systemd:
        daemon_reload: yes

    - name: Restart tomcat
      service:
        name: tomcat
        state: started

    - wait_for:
        timeout: 5

    - name: Check tomcat is running
      uri:
        url: http://{{inventory_host}}:{{tomcat_port}}/