
---
- name: Install tomcat
  hosts: target_nodes
  gather_facts: no
  
  tasks:
    - name: Check if Java is already installed
      shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
      register: java_version

    - debug:
        msg: Installed Java version is {{java_version.stdout}}
      when: java_version is success

    - name: Copy tomcat
      copy:
        src: files/apache-tomcat-8.0.32.tar.gz
        dest: /tmp/apache-tomcat-8.0.32.tar.gz

    - name: Create group tomcat
      group:
        name: tomcat
        state: present
    - name: Create user tomcat
      user:
        name: tomcat
        state: present

    - name: Create directory /usr/local/apache-tomcat-8.0.32
      file:
        path: /usr/local/apache-tomcat-8.0.32
        state: directory
        owner: tomcat
        group: tomcat
        mode: "0755"

    - name: Install tomcat
      unarchive:
        src:  /tmp/apache-tomcat-8.0.32.tar.gz
        dest: /usr/local/apache-tomcat-8.0.32
        remote_src: yes
        extra_opts: "--strip-components=1"
        owner: tomcat
        group: tomcat
        creates: /usr/local/apache-tomcat-8.0.32/bin
        mode: "0755"

    - name: Replace tomcat-users.xml file
      copy:
        src: files/tomcat-users.xml
        dest: /usr/local/apache-tomcat-8.0.32/conf/tomcat-users.xml
        owner: tomcat
        group: tomcat

    - name: Add startup script (systemd unit file)
      copy:
        src: files/tomcat.service
        dest: /etc/systemd/system/tomcat.service

    - name: Daemon reload
      systemd:
        daemon_reload: yes

    - name: Restart tomcat
      service:
        name: tomcat
        state: started

    - wait_for:
        timeout: 5

    - name: Check tomcat is running
      uri:
        url: http://10.66.205.140:8080