- name: Deploy Web Application
  hosts: target_nodes
  gather_facts: no

  tasks:
    - name: Remove current war file (if already deployed)
      file:
        path: "{{inst_root}}/apache-tomcat-{{tomcat_version}}/webapps/{{app_name}}.war"
        state: absent

    - name: Wait unitll the app is undeployed
      wait_for:
        path: "{{inst_root}}/apache-tomcat-{{tomcat_version}}/webapps/{{app_name}}"
        state: absent

    - name: Copy war file
      copy:
        src: files/{{app_name}}.war
        dest: "{{inst_root}}/apache-tomcat-{{tomcat_version}}/webapps/{{app_name}}.war"
        owner: tomcat
        group: tomcat

    - name: Wait unitll the app is deployed
      wait_for:
        path: "{{inst_root}}/apache-tomcat-{{tomcat_version}}/webapps/{{app_name}}"
        state: present

    - wait_for:
        timeout: 5

    - name: Check Application
      uri:
        url: http://{{inventory_host}}:{{tomcat_port}}/{{app_name}}/